---
title: "MusicInsight"
author: "Jonathan Cheon"
date: "9/17/2019"
output: html_document
---

```{r}

include <- function(library_name){
  if( !(library_name %in% installed.packages()) )
    suppressMessages(install.packages(library_name))
  library(library_name, character.only=TRUE)
}

include("tidyverse")
include("dplyr")

#Avoid absolute paths /Users/jcheon/...
#Use relative paths /
survey <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/music-survey.csv")
preferences <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/preferences-survey.csv")

```

Cleaning column names in Survey 
```{r}
colnames(survey)

#good for getting the source data and manipulating it yourself. 
colnames(survey)[colnames(survey)=="Timestamp"] <- "time_submitted"
colnames(survey)[colnames(survey)=="First, we are going to create a pseudonym for you to keep this survey anonymous (more or less). Which pseudonym generator would you prefer?"] <- "pseudonym_generator"
colnames(survey)[colnames(survey)=="What is your pseudonym?"] <- "pseudonym"
colnames(survey)[colnames(survey)=="Sex"] <- "sex"
colnames(survey)[colnames(survey)=="Major"] <- "academic_major"
colnames(survey)[colnames(survey)=="Academic Year"] <- "academic_level"
colnames(survey)[colnames(survey)=="Year you were born (YYYY)"] <- "year_born"
colnames(survey)[colnames(survey)=="Which musical instruments/talents do you play? (Select all that apply)"] <- "instrument"
colnames(survey)[colnames(survey)=="Song"] <- "favorite_song"
colnames(survey)[colnames(survey)=="Artist"] <- "favorite_song_artist"
colnames(survey)[colnames(survey)=="Link to song (on Youtube or Vimeo)"] <- "favorite_song_link"

colnames(survey)

```

```{r}
library(dplyr)
library(tidyr)
library(readr)

# person table
person <- tibble(pseudonym_generator=survey$pseudonym_generator, 
                 pseudonym=survey$pseudonym, 
                 year_born=survey$year_born, 
                 sex=survey$sex, 
                 academic_major=survey$academic_major, 
                 academic_level=survey$academic_level, 
                 time_submitted=survey$time_submitted)

person$time_submitted <- as.POSIXlt(parse_datetime(person$time_submitted, "%m/%d/%y %H:%M"))


#levels: 
# need to convert column to levels
levels(person$academic_level <- as.factor(person$academic_level))
levels(person$academic_level)

levels(person$academic_major <- as.factor(person$academic_major))
levels(person$academic_major)[levels(person$academic_major) == "Computer information systems"] <- "Computer Information Systems" #changing cases to correct cases. 
levels(person$academic_major)




# favorite song table
favoriteSong <- tibble(pseudonym=survey$pseudonym, 
                       artist=survey$favorite_song_artist,
                       song=survey$favorite_song, 
                       link=survey$favorite_song_link)

# ratings table 
ratings  <- gather(preferences, "artist_song", "rating", 3:45)
colnames(ratings)[colnames(ratings)=="What was your pseudonym?"] <- "pseudonym"
```


```{r}
instruments <- tibble(pseudonym=survey$pseudonym,
                      instruments=survey$instrument)

talents <- tibble(pseudonym=survey$pseudonym,
                      instruments=survey$instrument)

talents <- separate_rows(talents, -pseudonym, sep=",")

talents$instruments <- talents$instruments %>%
                        trimws() %>%
                        tolower() %>%
                        str_replace_all(pattern=".*piano.*", "piano") %>% #.* any character
                        str_replace_all(pattern=".*ukulele.*", "ukulele") %>%
                        as.factor()

```

```{r}
ggplot(ratings, aes(x=rating)) + geom_histogram(binwidth = 1)

ggplot(ratings, aes(x=mean(rating), y=pseudonym)) + 
  geom_boxplot() + 
  geom_vline(xintercept=mean(ratings$rating), linetype="dashed", color = "red")

mean(ratings$rating)

```


We found that two people made mistakes when identifying their pseudonyms for the ratings, 
*Angel Angel* and *Mission Theory*. Let's filter out the latter submissions from those users.

```{r}
#earliest_time <- min(ratings$time_rated[ratings$pseudonym=="Angel Angel"])
#ratings <- ratings %>% filter(!(pseudonym=="Angel Angel" & time_rated!=earliest_time))
#earliest_time <- min(ratings$time_rated[ratings$pseudonym=="Mission Theory"])
#ratings <- ratings %>% filter(!(pseudonym=="Mission Theory" & time_rated!=earliest_time))
```


```{r}
## Reconcile the difference between single- and double-column format of representing
## a song and its artist
ratings$artist_song <- str_replace_all(ratings$artist_song, 
                                       pattern = "\t", 
                                       replacement = " ")
# favorite_song$artist_song <- paste(favorite_song$artist, " ", favorite_song$title)
favorite_rating <- ratings %>% 
                    left_join(favoriteSong, by="pseudonym") %>%
                    filter(artist_song==paste(artist,song)) %>%
                    select(pseudonym,artist_song,rating)
print(favorite_rating)
```

And how did people rate their own favorite song?

```{r}
summary(favorite_rating$rating)
```


